### ISSUE TITLE
Improve the readability of the readme

### ISSUE THREAD

**Issue by samcaulfield** [samcaulfield/pml-studio#10]
The readme doesn't look very interesting. I propose:

1. Put the installation instructions first. The program has to be installed before the features can be tested.
2. Use markdown for headings, lists and commands to make them more readable.
3. Turn the paragraphs into lists of actions, so 

> Enter some PML into the editor. Click "Tools > Check syntax" to receive
> 	warning and error messages if there is a problem with your model. These
> 	messages are displayed to the left of the line numbers in the editor.

would become:

> 1. Enter some PML into the editor.
> 2. Click `Tools` in the navigation bar.
> 3. Click `Check syntax` in the tools menu.
> 4. Warning and error messages (if available) will be displayed to the left of the line numbers in the editor.

**Comment by Gulnur1** [comment]
Please don't make any changes, I am working on this

**Comment by samcaulfield** [comment]
Great, you can self-assign the issue to make it show up you're working on it.

**Comment by Gulnur1** [comment]
Can you check if everything looks good?

**Comment by Gulnur1** [comment]
I made it look better here on github, but when you actually download and open it, it looks a bit messy. I will change it.

**Comment by samcaulfield** [comment]
Looks good! Few small issues, e.g. "Access the IDE by visiting localhost/ in a web browser." there should be a <project name> after the localhost/. It will probably display better in a terminal if you keep the line lengths to max 80 or 100 characters.
