### ISSUE TITLE
Add keyboard shortcuts to save PML

### ISSUE THREAD

**Issue by samcaulfield** [samcaulfield/pml-studio#13]
This feature is on the product backlog. It is worth 20 points.

Requirements:

- There should be appropriate key bindings to download the PML file in Ace, Emacs and Vim modes.

- For Ace, the key binding is `Ctrl-S`

- For Vim, the command is `:w`

- For Emacs, the command is `C-x C-s`

**Comment by samcaulfield** [comment]
I just checked out the commit for this feature and can't get the described behaviour on Ubuntu 14.04.

**Comment by gallagts** [comment]
The desired behaviour should be
Save to disk: ctrl s ot ctrl s x
Open from disk ctrl o or ctrl f x
Save to server ctrl shift s
Open from server shift o
Run pml check ctrl r.

I'll look into it now.

**Comment by gallagts** [comment]
You have to be in ace editor, not just be on the apps page.

**Comment by gallagts** [comment]
As far as mine goes works fine. What exactly are you soing?

**Comment by samcaulfield** [comment]
I edited my post as I realised my mistake shortly after posting but I don't think you got an email about my edit. But yes, the issue was that the editor must be focused for it to receive the keys. We'll have to put a warning about this in the README.

**Comment by samcaulfield** [comment]
Are all of these features implemented and passing tests? If so this can be closed.

**Comment by Gulnur1** [comment]
I tested the shortcuts, everything seems to work, closing the issue

**Comment by gallagts** [comment]
Saving works. Still working on opening from disk. Opens into browser....

**Comment by Gulnur1** [comment]
It works

**Comment by Gulnur1** [comment]
Sorry just noticed that too

**Comment by sharonluk** [comment]
It doesn't seem to open file from disk properly. The other shortcuts seem to be working fine.

**Comment by gallagts** [comment]
Yes. Open from disk is the only one I am having trouble with.

**Comment by samcaulfield** [comment]
A keyboard shortcut for opening from disk is neither in the ticket description nor on the product backlog, so you can feel free to ignore it and close the issue if you'd rather work on more important things.

**Comment by samcaulfield** [comment]
The product backlog states:

> In emacs and vim modes, the respective editor's "save file" keybinding should save the file to the server.

@gallagts is the vim save command implemented?

**Comment by gallagts** [comment]
Not currently no. I am going to have another go at it thos evenng adter O
tidy up some things in some previous work.

**Comment by gallagts** [comment]
This may not be possible....
Web browsers have built in safe gaurds against a webpage taking a file from
a computer. I have tried to get around this, but so far I cannot seem to
get a keyboard event to prompt the user for a file to upload.

**Comment by samcaulfield** [comment]
I'm not sure what you mean exactly. All we need to implement is the vim `:w` command for saving a file. Once that is completed then this feature is finished.

**Comment by gallagts** [comment]
Do we not need to open a file via ctrl o as a feature?

**Comment by samcaulfield** [comment]
From the product backlog at http://jnoll.nfshost.com/cs4098/projects/rraptors-backlog.html

> In emacs and vim modes, the respective editor's "save file" keybinding should save the file to the server.

**Comment by gallagts** [comment]
Now saves for vim :w

**Comment by samcaulfield** [comment]
In what commit?

**Comment by gallagts** [comment]
I put it up just before I closed it.

**Comment by samcaulfield** [comment]
I don't see a commit for it. Did you push? https://github.com/samcaulfield/pml-studio/commits/master

**Comment by samcaulfield** [comment]
Since no reply was forthcoming and it's an hour before the deadline I implemented it myself in 62e75e0c549850cb3e2f426eb4ca428ce7110e7e
