### ISSUE TITLE
Displaying warning and error messages 

### ISSUE THREAD

**Issue by Gulnur1** [samcaulfield/pml-studio#14]
When `Check Syntax` is pressed, there should exist a way to show the user where the errors/warnings are.  
If there are multiple errors they need to be shown somewhere on the editor so that the user can press on the error and it jumps to where the error is.

**Comment by EamonMc** [comment]
I'm on these. I will work until they're completed today.

**Comment by EamonMc** [comment]
Ok this is done.

Warnings/errors now track to the first instance and I added a jquery notifications API 'noty' to thirdparty which looks pretty nice that we can probably use for other notifications also.
The user can also iterate over the warnings with 'previous' and ' next' buttons in the notification.

We can optionally display these notifications at the bottom as a bar either but for now I have set it to 'topCenter'.

**Comment by samcaulfield** [comment]
Awesome! Nice work. I like your point about using the notifications in other places.

I'm thinking we could add popups for actions like sign in and registration to show the result of the action, e.g. "Sign in successful", "Registration failed".

Feel free to close this issue and make other ones for adding popups in other places if you want.

**Comment by EamonMc** [comment]
Cheers. Closing this to make new issue with 'noty' notifications suggestions going forward and possible on previous features as it would not be hard to implement.
