### ISSUE TITLE
Multiple Identities

### ISSUE THREAD

**Issue by sharonluk** [samcaulfield/pml-studio#17]
One of the ideas brought up in the meeting was having multiple user identities while editing on the same browser.

**Comment by Gulnur1** [comment]
So one user has multiple accounts? `or multiple users can edit at the same time the same code?

**Comment by sharonluk** [comment]
I think it is a user having multiple accounts and editing the code on the browser at the same time.

**Comment by samcaulfield** [comment]
Any progress on this? Is this something we need to implement?

**Comment by sharonluk** [comment]
Since this issue hasn't been brought up again in recent meetings. We should focus on the features in the backlog and testing. I will close this issue.
