### ISSUE TITLE
Commit count error

### ISSUE THREAD

**Issue by mereckaj** [samcaulfield/pml-studio#23]
I was just checking your project out and noticed that the commit counter is broken. 

It says that @sharonluk  only has **3 commits** and **16 lines of code** added. Seems wrong.

Might be in your interest to fix this before release 2.

[Halp](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/)

**Comment by samcaulfield** [comment]
Thanks for the feedback mereckaj. This can be closed as it pertains to release 2, which we have reached now.
