### ISSUE TITLE
Implement agent coloured actions

### ISSUE THREAD

**Issue by samcaulfield** [samcaulfield/pml-studio#30]
This feature is on the product backlog. It is worth 8 points.

Description:
> Actions should be colored according to the value of the agent field, so it's clear which actions are performed by which agents. Actions with multiple agents should be striped, hashed, or similar with the colors of all agents involved.

**Comment by samcaulfield** [comment]
Is there progress to report for this? Otherwise we can take it off this release's milestone.

**Comment by sharonluk** [comment]
This won't be implemented in time , changes need to be made to the resource flow. For the swim lanes, the branches/iterations and selects still need to be worked on.

**Comment by sharonluk** [comment]
The feature is now implemented.
