### ISSUE TITLE
Headless Testing

### ISSUE THREAD

**Issue by samcaulfield** [samcaulfield/pml-studio#33]
It is possible to run Firefox in a virtual framebuffer using `xvfb`. I have tested it and our automated tests seem to work correctly with this setup. This allows us to run the tests without Firefox opening several times which a user may find confusing and annoying.

This means that to a user, it would look like our tests run purely from the commandline.

@Gulnur1 if you think this is a good idea I can go about implementing this. It only requires one extra dependency and an extra line at the beginning of `test.sh`.

**Comment by Gulnur1** [comment]
absolutely. I think it is a good idea and it might also reduce the time each test runs for.

**Comment by samcaulfield** [comment]
Implemented in 4259f4f98d5b40590aa24deec66e6b3fc95dcaa1
