### ISSUE TITLE
Implement graphical boxes & arrows editor

### ISSUE THREAD

**Issue by samcaulfield** [samcaulfield/pml-studio#5]
This feature is on the product backlog. It is worth 30 points.

**Comment by samcaulfield** [comment]
I don't know how successful we're going to be given the rate of progress so I've implemented a simple version to cover our bases for now in d8c97bb6e25cbd010eec8d0942377798cd508de4.

It just runs the PML through traverse and dot to get a PNG which is displayed alongside the PML.

**Comment by Gulnur1** [comment]
For some reason neither Check syntax nor the Visualise are working for me.

**Comment by Gulnur1** [comment]
Did you have to change anything in traverse?

**Comment by samcaulfield** [comment]
no, you'll have to rerun `make install-deps` for it to work though

**Comment by samcaulfield** [comment]
Sorry, I forgot to add a directory which was probably causing your problem. Added in d8c97bb6e25cbd010eec8d0942377798cd508de4

**Comment by Gulnur1** [comment]
it wrks now, great job!

**Comment by sharonluk** [comment]
Hey , just downloaded the latest version of the git file. 
When I click on visualize ,the tree doesn't seem to show up, were changes made since the last meeting? 
Trying to figure out how to get the tree to convert into Json file and back into PML code.

**Comment by samcaulfield** [comment]
The latest commit under this ticket (f68b3b352915792f3adecb3fc30e614a9d6e835f) features a graphical editor with support for placing actions, branches and selections.

The remaining required functionality is:

- Iterations.

- Arrows connecting the process components.

**Comment by samcaulfield** [comment]
Implemented in fd711cb1b4372167e848129d2c5de4ce41a7218c
