### ISSUE TITLE
Clean up project structure

### ISSUE THREAD

**Issue by samcaulfield** [samcaulfield/pml-studio#8]
The project structure is messy. This makes it take longer than it should to find files.

Actions:
1. Remove unnecessary files.
2. Put PHP and JavaScript files in their own directories.
3. Port the build system to GNU Make (puts all the maintenance scripts in a single Makefile).
4. Put the PML models in their own directory.

**Comment by Gulnur1** [comment]
What are the unnecessary files?

**Comment by samcaulfield** [comment]
They were some CSS files left over from the old UI. I removed them in b45969feec8404babba23f95680ba8a44dc63360

**Comment by samcaulfield** [comment]
Added the models directory in ecf350fd1d788470a8ad8d2a344134df874c9d8b, but I'm not sure how necessary this is. We install peos as a dependency which comes with its own models. We could just use those instead.

**Comment by samcaulfield** [comment]
Added the JS subdirectory in dab142d3f25dd735d2c2cdc389ceae6d63df4137 and the PHP subdirectory in 5e66f6988b37bb1bce252d0e51d4f4b298e64969.

**Comment by samcaulfield** [comment]
Added Makefile in 7a0b02f8fb48538936bc4ccb7652cd13ab4635e6.
